#! /usr/bin/perl

use Date::Business;
use TokyoCabinet;
use Getopt::Long;
use DBI;

GetOptions('startdate=s' => \$sdate, 'list=s' => \$tickers, 'todir=s' => \$cabdir);

#create epoch starting 1/2/1950
#have to do it in stages because of Date::Business
#not being able to handle dates before Unix Epoch

$d1 = new Date::Business(DATE => "19700101");
$d1->subb(5218);

$dbh = DBI->connect("DBI:mysql:finance", "perldb");
$sh = $dbh->prepare("select * from historical where ticker = ? and date >= '$sdate'");
$si = $dbh->prepare("select date,bef,after from splits where ticker = ? and date >= '$sdate'");
$di = $dbh->prepare("select date,divamt from dividends where ticker = ? and date >= '$sdate'");
$fp = $dbh->prepare("select * from fundamentals where ticker = ? and quarter_date >= '$sdate'");

open INFILE, $tickers;
chdir $cabdir;

my $index = TokyoCabinet::HDB->new();
$index->open("epoch-index", $index->OWRITER | $index->OCREAT);

my $splits = TokyoCabinet::HDB->new();
$splits->open("splits", $splits->OWRITER | $splits->OCREAT);

my $dividends = TokyoCabinet::HDB->new();
$dividends->open("dividends", $dividends->OWRITER | $dividends->OCREAT);

my $fdates = TokyoCabinet::HDB->new();
$fdates->open("fund-dates", $fdates->OWRITER | $fdates->OCREAT);

my $fdata = TokyoCabinet::FDB->new();
$fdata->tune(80);
$fdata->open("fund-data", $fdata->OWRITER | $fdata->OCREAT);

foreach(<INFILE>) {
    
    chomp;
    print "\n$_";
    my $basedate = save_history_tocab($_);
    save_splits_tocab($_, $basedate);
    save_dividends_tocab($_, $basedate);
    save_fundamentals_tocab($_);
}

$dividends->close();
$splits->close();
$fdates->close();
$fdata->close();
$index->close();

sub save_history_tocab {

    my $ticker = shift;

    $sh->execute($ticker);
    $res = $sh->fetchall_arrayref();
    my $baseday = get_epoch_date($res->[0][0]);
    $index->putkeep($ticker, $baseday);

    my $fdb = TokyoCabinet::FDB->new();
    $fdb->tune(36);
    
    my $fname = $ticker;
    $fname =~ tr/\//:/;
    $fdb->open($fname, $fdb->OWRITER | $fdb->OCREAT);
    
    foreach (@$res) {
    	        
		$day = get_epoch_date($_->[0]);
		$id = $day - $baseday;	
		@foo = ($_->[2],$_->[3],$_->[4],$_->[5],$_->[6]);
		$fdb->put($id + 1, pack("FFFFL", @foo));
    }

    $fdb->close();
    return $baseday;
}

sub save_splits_tocab {

    my $ticker = shift;
    my $baseday = shift;
    my $sdata;

    $si->execute($ticker);
    $res = $si->fetchall_arrayref();

    foreach(@$res) {
        my $splitdate = get_epoch_date(@$_[0]) - $baseday;
	@$_[0] = $splitdate;
	my $s =	 pack("LSS", @$_);
	$sdata .= $s;	     
    } 

    $splits->putcat($ticker, $sdata);
}

sub save_dividends_tocab {

    my $ticker = shift;
    my $baseday = shift;
    my $divdata;

    $di->execute($ticker);
    $divs = $di->fetchall_arrayref();

    foreach(@$divs) {
       my $divdate = get_epoch_date(@$_[0]) - $baseday;
       @$_[0] = $divdate;
       my $dat = pack("LF", @$_);
       $divdata .= $dat;
    }   

    $dividends->putcat($ticker, $divdata);
}

sub save_fundamentals_tocab {

    my $ticker = shift;
    my $keydata = "";

    $fp->execute($ticker);
    my $data = $fp->fetchall_hashref('quarter_date');

    foreach $date (reverse sort keys %$data) {
       
       my $day = get_epoch_date($date);
       my $idx = $fdata->rnum() + 1;
       my $d = $data->{$date};

       $keydata .= pack("LL", $day, $idx);
       my $fundrow = pack("QQQQQQQQLLF", $d->{'total_assets'}, $d->{'current_assets'},
       	    	        $d->{'total_debt'}, $d->{'current_debt'}, $d->{'cash'}, $d->{'revenue'},
					         $d->{'avg_shares_diluted'}, $d->{'shares_outstanding'}, $d->{'equity'},
						 			          $d->{'net_income'}, $d->{'eps_diluted'});

       $fdata->put($idx, $fundrow);       
    }

    $fdates->putcat($ticker, $keydata);
}

sub get_epoch_date {

    my $date = shift;
    $date =~ s/-//g;
    
    my $d2 = new Date::Business(DATE => $date);
    return $d2->diffb($d1);
}

